apiVersion: v1
kind: Service
metadata:
  name: python-na-cloud
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: python-na-cloud
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: python-na-cloud
spec:
  backend:
    serviceName: python-na-cloud
    servicePort: 5000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python-na-cloud
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: python-na-cloud
    spec:
      containers:
        - name: python-na-cloud
          image: python-na-cloud:latest
          imagePullPolicy: Never
          # envFrom:
          #   - configMapRef:
          #       name: python-na-cloud-env
          #   - secretRef:
          #       name: python-na-cloud-secrets
          ports:
          - containerPort: 5000